sudo: false
language: generic

os:
  - osx
  - linux
osx_image: xcode6.4

git:
  depth: 200

script:
- travis_wait 40 ./build.sh

after_success:
- ls -ahl
# Decrypt the private key from the travis env variable and copy into ~/.ssh
- openssl rsa -in .ssh/id_rsa.enc -out .ssh/id_rsa -passin env:DEPLOY_KEYPASS
- rm .ssh/id_rsa.enc
- cp -r .ssh ~/
- chmod 600 ~/.ssh/id_rsa
- scp menpo_playground.tar.xz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

notifications:
  slack:
    rooms:
      - menpo:19gyWImMkOfCj0iDAgTbDlDA
    on_success: :change
    on_failure: :change
  email: false
